networks:
  light_feather_net:
    driver: bridge

services:

  api:
    build:
      context: .
      dockerfile: LightFeather.CodeChallenge.Api/Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - light_feather_net
  ui:
    build:
      context: .
      dockerfile: LightFeather.CodeChallenge.Ui/Dockerfile
    depends_on:
      - api
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost/health || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
    ports:
      - "80:80"
      - "443:443"
    networks:
      - light_feather_net